using System.Linq;
using System.Numerics;
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Components;
using Content.Shared.Access.Systems;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Input;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Sunset.Research;

/// <summary>
/// 🌇Sunset🌇 - branching tech tree R&amp;D console: a pannable/zoomable canvas of
/// ResearchTreeNodeControl cards, connected by prerequisite lines drawn by ResearchTreeCanvas, with
/// a side panel showing the selected node's details. Replaces the old flat card-list console.
/// Layout/interaction concept ported from Goob-Station's FancyResearchConsoleMenu, rebuilt against
/// our own TechnologyPrototype data (with discipline/tier gating preserved, see ResearchSystem.Console.cs).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ResearchTreeMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;

    public Action<string>? OnTechnologyCardPressed;
    public Action? OnServerButtonPressed;

    public EntityUid Entity;
    public ProtoId<TechnologyPrototype>? CurrentTech;
    public Dictionary<string, ResearchAvailability> List = new();
    public int Points;

    private bool _dragging;
    private static readonly Vector2 DefaultPanOffset = new(40, 140);
    private Vector2 _panOffset = DefaultPanOffset;
    private float _zoom = 1f;
    private const float MinZoom = 0.8f;
    private const float MaxZoom = 2f;
    private const float ZoomStep = 0.125f;
    private const float CellSize = 100f;

    /// <summary>
    /// Every canvas control (tech nodes + discipline headers) with its normalized grid position,
    /// so pan/zoom/recenter can re-place all of them from one source of truth.
    /// </summary>
    private readonly List<(Control Control, Vector2 GridPos)> _layoutEntries = new();

    public ResearchTreeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        RecenterButton.OnPressed += _ => Recenter();
        DragContainer.OnKeyBindDown += OnDragKeyDown;
        DragContainer.OnKeyBindUp += OnDragKeyUp;
    }

    public void SetEntity(EntityUid entity) => Entity = entity;

    public void UpdatePanels(Dictionary<string, ResearchAvailability> researches)
    {
        DragContainer.RemoveAllChildren();
        _layoutEntries.Clear();
        List = researches;

        // The yaml positions put every discipline on one long shared Y axis with big gaps
        // (industrial at Y 0-8, arsenal at 15-25, experimental at 30-36, civilian at 45-51), which
        // made a ~50-row-tall strip needing endless scrolling. Instead, re-base each discipline to
        // (0,0) and lay the disciplines out side by side as their own labeled branch columns.
        var byDiscipline = new Dictionary<string, List<(TechnologyPrototype Proto, ResearchAvailability Availability)>>();
        foreach (var (techId, availability) in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(techId);
            if (proto.Hidden)
                continue;

            byDiscipline.GetOrNew(proto.Discipline.Id).Add((proto, availability));
        }

        var xCursor = 0f;
        foreach (var disciplineId in byDiscipline.Keys.OrderBy(x => x))
        {
            var entries = byDiscipline[disciplineId];
            var minX = entries.Min(e => e.Proto.Position.X);
            var minY = entries.Min(e => e.Proto.Position.Y);
            var width = entries.Max(e => e.Proto.Position.X) - minX + 1;

            var discipline = _prototype.Index<TechDisciplinePrototype>(disciplineId);
            var header = new Label
            {
                Text = Loc.GetString(discipline.Name),
                FontColorOverride = discipline.Color,
            };
            DragContainer.AddChild(header);
            AddLayoutEntry(header, new Vector2(xCursor + width / 2f - 0.5f, -0.9f));

            foreach (var (proto, availability) in entries)
            {
                var node = new ResearchTreeNodeControl(proto, availability, _sprite);
                node.OnSelected += SelectTech;
                DragContainer.AddChild(node);
                AddLayoutEntry(node, new Vector2(xCursor - minX, -minY) + proto.Position);

                if (proto.ID == CurrentTech)
                    SelectTech(proto, availability);
            }

            xCursor += width + 1f;
        }
    }

    private void AddLayoutEntry(Control control, Vector2 gridPos)
    {
        _layoutEntries.Add((control, gridPos));
        LayoutContainer.SetPosition(control, _panOffset + gridPos * CellSize * _zoom);
    }

    private void Relayout()
    {
        foreach (var (control, gridPos) in _layoutEntries)
        {
            LayoutContainer.SetPosition(control, _panOffset + gridPos * CellSize * _zoom);
        }
    }

    public void UpdateInformationPanel(int points)
    {
        Points = points;

        var amountMsg = new FormattedMessage();
        amountMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text", ("points", points)));
        ResearchAmountLabel.SetMessage(amountMsg);

        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        var disciplineText = Loc.GetString("research-discipline-none");
        var disciplineColor = Color.Gray;
        if (database.MainDiscipline != null)
        {
            var mainDiscipline = _prototype.Index<TechDisciplinePrototype>(database.MainDiscipline);
            disciplineText = Loc.GetString(mainDiscipline.Name);
            disciplineColor = mainDiscipline.Color;
        }

        var mainMsg = new FormattedMessage();
        mainMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-main-discipline",
            ("name", disciplineText), ("color", disciplineColor)));
        MainDisciplineLabel.SetMessage(mainMsg);

        TierDisplayContainer.RemoveAllChildren();
        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index<TechDisciplinePrototype>(disciplineId);
            var tier = _research.GetHighestDisciplineTier(database, discipline);
            if (tier == 0)
                continue;

            var texture = new TextureRect { TextureScale = new Vector2(2, 2), VerticalAlignment = VAlignment.Center };
            texture.Texture = _sprite.Frame0(discipline.Icon);
            var label = new RichTextLabel();
            label.SetMessage(Loc.GetString("research-console-tier-info-small", ("tier", tier)));

            TierDisplayContainer.AddChild(new BoxContainer
            {
                Children = { texture, label, new Control { MinWidth = 10 } },
            });
        }
    }

    public void SelectTech(TechnologyPrototype proto, ResearchAvailability availability)
    {
        InfoContainer.RemoveAllChildren();
        if (_player.LocalEntity is not { } local)
            return;

        CurrentTech = proto.ID;
        var hasAccess = !_entity.TryGetComponent<AccessReaderComponent>(Entity, out var access) ||
                         _accessReader.IsAllowed(local, Entity, access);

        var panel = new ResearchTreeInfoPanel(proto, hasAccess, availability, _sprite);
        panel.OnBuyPressed += p => OnTechnologyCardPressed?.Invoke(p.ID);
        InfoContainer.AddChild(panel);
    }

    public void Recenter()
    {
        _panOffset = DefaultPanOffset;
        _zoom = 1f;
        Relayout();
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_dragging)
            return;

        _panOffset += args.Relative;
        foreach (var child in DragContainer.Children)
        {
            LayoutContainer.SetPosition(child, child.Position + args.Relative);
        }
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        var oldZoom = _zoom;
        _zoom = Math.Clamp(_zoom + (args.Delta.Y > 0 ? ZoomStep : -ZoomStep), MinZoom, MaxZoom);

        if (MathHelper.CloseTo(oldZoom, _zoom))
            return;

        Relayout();
        args.Handle();
    }

    private void OnDragKeyDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _dragging = true;
    }

    private void OnDragKeyUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _dragging = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        => _dragging ? DragMode.None : base.GetDragModeFor(relativeMousePos);

    public override void Close()
    {
        base.Close();

        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
    }
}
