using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunset.Research;

/// <summary>
/// 🌇Sunset🌇 - a single node card on the branching tech tree console, positioned by
/// ResearchTreeMenu at TechnologyPrototype.Position and colored by its ResearchAvailability.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ResearchTreeNodeControl : LayoutContainer
{
    public readonly TechnologyPrototype Prototype;
    public readonly ResearchAvailability Availability;
    public event Action<TechnologyPrototype, ResearchAvailability>? OnSelected;

    private readonly Color _color;
    private readonly Color _hoveredColor;
    private readonly Color _borderColor;

    public ResearchTreeNodeControl(TechnologyPrototype proto, ResearchAvailability availability, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        Prototype = proto;
        Availability = availability;

        IconTexture.Texture = sprite.Frame0(proto.Icon);
        NodeButton.OnPressed += _ => OnSelected?.Invoke(Prototype, Availability);
        NodeButton.OnDrawModeChanged += UpdatePanelColor;

        (_color, _hoveredColor, _borderColor) = availability switch
        {
            ResearchAvailability.Researched => (Color.FromHex("#1F3D1F"), Color.FromHex("#7CFF7C"), Color.LimeGreen),
            ResearchAvailability.Available => (Color.FromHex("#4A4A16"), Color.FromHex("#ECFA52"), Color.FromHex("#E8FA25")),
            ResearchAvailability.PrereqsMet => (Color.FromHex("#40310F"), Color.FromHex("#FAD398"), Color.FromHex("#CCA031")),
            _ => (Color.FromHex("#3D1414"), Color.FromHex("#FF8A8A"), Color.Crimson),
        };

        UpdatePanelColor();
    }

    private void UpdatePanelColor()
    {
        var box = (StyleBoxFlat) Panel.PanelOverride!;
        box.BackgroundColor = NodeButton.IsHovered ? _hoveredColor : _color;
        box.BorderColor = _borderColor;
    }
}

/// <summary>
/// 🌇Sunset🌇 - a Button that exposes DrawModeChanged (hover/press state) so ResearchTreeNodeControl
/// can re-tint its panel on hover without polling every frame.
/// </summary>
public sealed class ResearchTreeNodeButton : Button
{
    public event Action? OnDrawModeChanged;

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();
        OnDrawModeChanged?.Invoke();
    }
}
