using Content.Client.Research;
using Content.Client.Research.UI;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunset.Research;

/// <summary>
/// 🌇Sunset🌇 - side panel shown when a node is selected on the branching tech tree console: full
/// name/icon/discipline/cost, prerequisite mini-cards (reusing the vanilla control), a text list of
/// unlocks, and the buy button.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ResearchTreeInfoPanel : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public readonly TechnologyPrototype Prototype;
    public event Action<TechnologyPrototype>? OnBuyPressed;

    public ResearchTreeInfoPanel(TechnologyPrototype proto, bool hasAccess, ResearchAvailability availability, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Prototype = proto;
        var research = _entity.System<ResearchSystem>();
        var discipline = _prototype.Index(proto.Discipline);

        TechnologyNameLabel.Text = Loc.GetString(proto.Name);
        TechnologyTexture.Texture = sprite.Frame0(proto.Icon);
        DisciplineTexture.Texture = sprite.Frame0(discipline.Icon);

        var tierMsg = new Robust.Shared.Utility.FormattedMessage();
        tierMsg.AddMarkupOrThrow(Loc.GetString("research-console-tier-discipline-info",
            ("tier", proto.Tier), ("color", discipline.Color), ("discipline", Loc.GetString(discipline.Name))));
        TierLabel.SetMessage(tierMsg);

        var costColor = availability switch
        {
            ResearchAvailability.PrereqsMet => Color.Crimson,
            ResearchAvailability.Unavailable => Color.Crimson,
            _ => (Color?) null,
        };
        TechnologyCostLabel.SetMessage(Loc.GetString("research-console-cost", ("amount", proto.Cost)), defaultColor: costColor);

        NoPrereqLabel.Visible = proto.TechnologyPrerequisites.Count == 0;
        PrereqsContainer.Visible = !NoPrereqLabel.Visible;
        RequiredTechContainer.RemoveAllChildren();
        foreach (var techId in proto.TechnologyPrerequisites)
        {
            var tech = _prototype.Index(techId);
            RequiredTechContainer.AddChild(new MiniTechnologyCardControl(tech, _prototype, sprite, research.GetTechnologyDescription(tech)));
        }

        UnlocksLabel.SetMessage(research.GetTechnologyDescription(proto, includeCost: false, includeTier: false, includePrereqs: false));

        ResearchButton.ToolTip = hasAccess ? null : Loc.GetString("research-console-no-access-popup");
        ResearchButton.Text = availability == ResearchAvailability.Researched
            ? Loc.GetString("research-tree-researched-button")
            : Loc.GetString("research-tree-buy-button");
        ResearchButton.Disabled = !hasAccess || availability != ResearchAvailability.Available;
        ResearchButton.OnPressed += _ => OnBuyPressed?.Invoke(Prototype);
    }
}
