// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Sunset.Arena;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Sunset.Arena;

[GenerateTypedNameReferences]
public sealed partial class ArenaWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    private ArenaSystem? _arena;
    private bool _subscribed;

    private ArenaState _state = ArenaState.Idle;
    private int _participants;
    private float _timeLeft;
    private bool _inQueue;

    public ArenaWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // NOTE: this window is constructed while the game screen is being built, which is before
        // entity systems are available. We therefore resolve the arena system lazily (see TryGetArena)
        // instead of in the constructor.

        InfoLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("arena-window-info")));

        ModeButton.AddItem(Loc.GetString("arena-mode-melee"), (int) ArenaMode.Melee);
        ModeButton.AddItem(Loc.GetString("arena-mode-meleeranged"), (int) ArenaMode.MeleeRanged);
        ModeButton.AddItem(Loc.GetString("arena-mode-ranged"), (int) ArenaMode.Ranged);
        ModeButton.OnItemSelected += args => ModeButton.SelectId(args.Id);

        CreateButton.OnPressed += _ =>
        {
            if (TryGetArena(out var arena))
                arena.Create((ArenaMode) ModeButton.SelectedId);
        };
        JoinButton.OnPressed += _ =>
        {
            if (TryGetArena(out var arena))
                arena.Join();
        };
        SpectateButton.OnPressed += _ =>
        {
            if (TryGetArena(out var arena))
                arena.Spectate();
        };

        UpdateControls();
    }

    private bool TryGetArena([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out ArenaSystem? arena)
    {
        if (_arena != null)
        {
            arena = _arena;
            return true;
        }

        if (_entMan.TrySystem(out _arena))
        {
            // First time we got the system: start listening and sync with the current state.
            if (!_subscribed)
            {
                _arena.StatusChanged += OnStatusChanged;
                _subscribed = true;

                if (_arena.LastStatus is { } status)
                    OnStatusChanged(status);
            }

            arena = _arena;
            return true;
        }

        arena = null;
        return false;
    }

    private void OnStatusChanged(ArenaStatusEvent ev)
    {
        _state = ev.State;
        _participants = ev.Participants;
        _timeLeft = ev.TimeLeft;
        _inQueue = ev.InQueue;
        UpdateControls();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // Lazily hook up to the arena system once it becomes available.
        TryGetArena(out _);

        if (_state != ArenaState.Queueing)
            return;

        _timeLeft -= args.DeltaSeconds;
        if (_timeLeft < 0f)
            _timeLeft = 0f;

        StatusLabel.Text = Loc.GetString("arena-status-queueing",
            ("count", _participants), ("time", $"{_timeLeft:0}"));
    }

    private void UpdateControls()
    {
        var idle = _state == ArenaState.Idle;
        ModeButton.Disabled = !idle;
        CreateButton.Disabled = !idle;

        // While queueing the Join button doubles as a Leave button (toggle, like the lobby Ready button).
        JoinButton.Visible = _state == ArenaState.Queueing;
        JoinButton.Text = _inQueue
            ? Loc.GetString("arena-leave-button")
            : Loc.GetString("arena-join-button", ("count", _participants));
        SpectateButton.Visible = _state == ArenaState.Fighting;

        StatusLabel.Text = _state switch
        {
            ArenaState.Idle => Loc.GetString("arena-status-idle"),
            ArenaState.Queueing => Loc.GetString("arena-status-queueing",
                ("count", _participants), ("time", $"{_timeLeft:0}")),
            ArenaState.Fighting => Loc.GetString("arena-status-fighting", ("count", _participants)),
            ArenaState.Cooldown => Loc.GetString("arena-status-cooldown"),
            _ => string.Empty,
        };
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing && _arena != null && _subscribed)
            _arena.StatusChanged -= OnStatusChanged;
    }
}
