using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminMenuWindow : DefaultWindow
{
    public event Action? OnDisposed;

    public AdminMenuWindow()
    {
        MinSize = new Vector2(650, 250);
        Title = Loc.GetString("admin-menu-title");
        RobustXamlLoader.Load(this);
        MasterTabContainer.SetTabTitle((int) TabIndex.Admin, Loc.GetString("admin-menu-admin-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Adminbus, Loc.GetString("admin-menu-adminbus-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Atmos, Loc.GetString("admin-menu-atmos-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Round, Loc.GetString("admin-menu-round-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Server, Loc.GetString("admin-menu-server-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.PanicBunker, Loc.GetString("admin-menu-panic-bunker-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Players, Loc.GetString("admin-menu-players-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Objects, Loc.GetString("admin-menu-objects-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Playtime, Loc.GetString("admin-menu-playtime-tab")); // 🌇Sunset🌇
        MasterTabContainer.SetTabTitle((int) TabIndex.FakePlayerCount, Loc.GetString("admin-menu-fake-player-count-tab")); // 🌇Sunset🌇
        MasterTabContainer.SetTabVisible((int) TabIndex.FakePlayerCount, false); // 🌇Sunset🌇 - shown only for Host, see AdminUIController
        MasterTabContainer.OnTabChanged += OnTabChanged;
    }

    // 🌇Sunset🌇 - the fake player count tab is Host-only; AdminUIController calls this whenever admin status changes.
    public void SetFakePlayerCountTabVisible(bool visible)
    {
        MasterTabContainer.SetTabVisible((int) TabIndex.FakePlayerCount, visible);
    }

    private void OnTabChanged(int tabIndex)
    {
        var tabEnum = (TabIndex)tabIndex;
        if (tabEnum == TabIndex.Objects)
            ObjectsTabControl.RefreshObjectList();
    }

    protected override void Dispose(bool disposing)
    {
        OnDisposed?.Invoke();
        base.Dispose(disposing);
        OnDisposed = null;
    }

    private enum TabIndex
    {
        Admin = 0,
        Adminbus,
        Atmos,
        Round,
        Server,
        PanicBunker,
        Players,
        Objects,
        Playtime, // 🌇Sunset🌇
        FakePlayerCount, // 🌇Sunset🌇
    }
}
