using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    public GhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    public event Action? NewLifePressed;   //🌟Starlight🌟
    public event Action? CharacterEditorPressed;   //🌟Starlight🌟
    public event Action? GhostThemePressed;   //🌟Starlight🌟
    public event Action? ArenaPressed;   // 🌇Sunset🌇

    private int _prevNumberRoles;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleClass.Negative);
        NewLifeButton.OnPressed += _ => NewLifePressed?.Invoke(); //🌟Starlight🌟
        CharacterEditorButton.OnPressed += _ => CharacterEditorPressed?.Invoke(); //🌟Starlight🌟
        GhostThemeButton.OnPressed += _ => GhostThemePressed?.Invoke(); //🌟Starlight🌟
        ArenaButton.OnPressed += _ => ArenaPressed?.Invoke(); // 🌇Sunset🌇
        NewLifeButton.StyleClasses.Add(StyleClass.Negative);  //🌟Starlight🌟
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    public void Update(int? roles, bool? canReturnToBody)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleClass.Negative);
            }

            _prevNumberRoles = (int)roles;
        }

        TargetWindow.Populate();
    }

    // 🌇Sunset🌇 - shows a live participant count on the button while a match is being gathered,
    // e.g. "Арена (3)", so ghosts can tell there's something to join without opening the window.
    public void UpdateArena(int? queueingCount)
    {
        ArenaButton.Text = queueingCount is { } count
            ? Loc.GetString("ghost-gui-arena-button-active", ("count", count))
            : Loc.GetString("ghost-gui-arena-button");
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }
}
