using Content.Client.Message;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunset.SponsorUplink;

/// <summary>
/// A single Sponsor Uplink item card: bordered frame, icon in the middle, name above it,
/// description and a buy button below - as opposed to the vanilla StoreListingControl's
/// horizontal list row.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SponsorUplinkListingControl : Control
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action? OnBuyPressed;

    public SponsorUplinkListingControl(ListingDataWithCostModifiers data, string priceText, bool hasBalance, Texture? texture)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        ItemName.Text = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(data, _prototype);
        ItemDescription.SetMessage(ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(data, _prototype));
        ItemTexture.Texture = texture;
        ItemPrice.Text = priceText;
        BuyButton.Disabled = !hasBalance;
        BuyButton.Label.FontColorOverride = Color.FromHex("#FFF3D6");

        BuyButton.OnButtonDown += _ => OnBuyPressed?.Invoke();
    }
}
