using System.Linq;
using Content.Client.Message;
using Content.Client.Store.Ui;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunset.SponsorUplink;

/// <summary>
/// Purple/orange-themed window for the Sponsor Uplink. Unlike the vanilla StoreMenu's list rows,
/// listings render as cards (frame + icon + name + description + buy button) in a grid, one
/// category shown at a time via a row of tab buttons - similar shape to the Syndicate uplink's
/// tabbed layout, just re-skinned and re-laid-out for a nicer cosmetics-shop feel.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SponsorUplinkMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<ListingDataWithCostModifiers>? OnListingButtonPressed;
    public event Action<string, int>? OnWithdrawAttempt;

    private static readonly Color TabUnselectedBg = Color.FromHex("#3D1F05");
    private static readonly Color TabSelectedBg = Color.FromHex("#A64DFF");
    private static readonly Color TabBorder = Color.FromHex("#FFD23F");
    private static readonly Color TabSelectedText = Color.FromHex("#FFF3D6");
    private static readonly Color TabUnselectedText = Color.FromHex("#F2D9B8");

    private StoreWithdrawWindow? _withdrawWindow;
    private Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> _balance = new();

    private List<ListingDataWithCostModifiers> _listings = new();
    private ProtoId<StoreCategoryPrototype>? _currentCategory;

    private const int MinColumns = 1;
    private const int MaxColumns = 10;

    public SponsorUplinkMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WithdrawButton.OnButtonDown += OnWithdrawButtonDown;
        OnResized += ProcessResize;
    }

    public void UpdateBalance(Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> balance)
    {
        _balance = balance;

        var balanceStr = string.Empty;
        foreach (var (currencyId, amount) in balance)
        {
            var currency = _prototypeManager.Index(currencyId);
            balanceStr += Loc.GetString("store-ui-balance-display", ("amount", amount),
                ("currency", Loc.GetString(currency.DisplayName, ("amount", 1)))) + "\n";
        }

        BalanceInfo.SetMarkup(balanceStr.TrimEnd());

        var canWithdraw = balance.Any(b => _prototypeManager.Index(b.Key).CanWithdraw && b.Value > 0);
        WithdrawButton.Disabled = !canWithdraw;
    }

    public void UpdateListings(List<ListingDataWithCostModifiers> listings)
    {
        _listings = listings;

        var categories = listings
            .SelectMany(l => l.Categories)
            .Distinct()
            .Where(c => _prototypeManager.HasIndex(c))
            .OrderBy(c => _prototypeManager.Index(c).Priority)
            .ToList();

        if (_currentCategory == null || !categories.Contains(_currentCategory.Value))
            _currentCategory = categories.FirstOrDefault();

        CategoryButtonsContainer.RemoveAllChildren();
        foreach (var category in categories)
        {
            var selected = category == _currentCategory;
            var button = new Button
            {
                Text = Loc.GetString(_prototypeManager.Index(category).Name),
                ToggleMode = true,
                Pressed = selected,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 2, 0),
                Label = { FontColorOverride = selected ? TabSelectedText : TabUnselectedText },
                StyleBoxOverride = new StyleBoxFlat
                {
                    BackgroundColor = selected ? TabSelectedBg : TabUnselectedBg,
                    BorderColor = TabBorder,
                    BorderThickness = new Thickness(0, 0, 0, selected ? 0 : 2),
                },
            };
            var capturedCategory = category;
            button.OnButtonDown += _ =>
            {
                _currentCategory = capturedCategory;
                UpdateListings(_listings);
            };
            CategoryButtonsContainer.AddChild(button);
        }

        RefreshGrid();
    }

    private void RefreshGrid()
    {
        ListingsGrid.RemoveAllChildren();

        var spriteSys = _entityManager.System<SpriteSystem>();

        var currentCategory = _currentCategory;
        var shown = _listings
            .Where(l => currentCategory != null && l.Categories.Contains(currentCategory.Value))
            .OrderBy(l => l.Priority)
            .ThenBy(l => l.Cost.Values.Sum());

        foreach (var listing in shown)
        {
            var hasBalance = listing.CanBuyWith(_balance);

            Texture? texture = null;
            if (listing.Icon != null)
                texture = spriteSys.Frame0(listing.Icon);
            else if (listing.ProductEntity != null)
                texture = spriteSys.GetPrototypeIcon(listing.ProductEntity).Default;

            var priceText = GetListingPriceString(listing);

            var card = new SponsorUplinkListingControl(listing, priceText, hasBalance, texture);
            card.OnBuyPressed += () => OnListingButtonPressed?.Invoke(listing);
            ListingsGrid.AddChild(card);
        }

        ProcessResize();
    }

    // Recomputes how many card columns fit the current window width, so widening the window (or
    // starting it wide) lays out more cards per row instead of leaving the grid cramped at a fixed
    // column count.
    private void ProcessResize()
    {
        if (ListingsGrid.ChildCount == 0)
            return;

        var itemWidth = 0f;
        foreach (var child in ListingsGrid.Children)
            itemWidth = Math.Max(itemWidth, child.Size.X);

        if (itemWidth <= 0)
            return;

        var columns = (int) (ListingsGrid.Size.X / itemWidth);
        columns = Math.Clamp(columns, MinColumns, MaxColumns);

        ListingsGrid.Columns = columns;
    }

    private string GetListingPriceString(ListingDataWithCostModifiers listing)
    {
        if (listing.Cost.Count < 1)
            return Loc.GetString("store-currency-free");

        var text = string.Empty;
        foreach (var (type, amount) in listing.Cost)
        {
            var currency = _prototypeManager.Index(type);
            text += Loc.GetString("store-ui-price-display", ("amount", amount),
                ("currency", Loc.GetString(currency.DisplayName, ("amount", amount))));
        }

        return text.TrimEnd();
    }

    private void OnWithdrawButtonDown(BaseButton.ButtonEventArgs args)
    {
        if (_withdrawWindow is { IsOpen: true })
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        _withdrawWindow = new StoreWithdrawWindow();
        _withdrawWindow.OpenCentered();
        _withdrawWindow.CreateCurrencyButtons(_balance);
        _withdrawWindow.OnWithdrawAttempt += (_, currency, amount) => OnWithdrawAttempt?.Invoke(currency, amount);
    }
}
