using Content.Shared._Starlight.Plumbing;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client._Starlight.Plumbing.UI;

[GenerateTypedNameReferences]
public sealed partial class PlumbingSynthesizerWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<bool>? OnToggle;
    public event Action<string?>? OnSelectReagent;

    private bool _enabled = true;
    private readonly Dictionary<int, string> _reagentIndexMap = new();

    public PlumbingSynthesizerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ToggleStatusButton.OnPressed += _ =>
        {
            _enabled = !_enabled;
            UpdateToggleButton();
            OnToggle?.Invoke(_enabled);
        };

        ReagentSelector.OnItemSelected += args =>
        {
            if (args.Id == 0)
            {
                OnSelectReagent?.Invoke(null);
            }
            else if (_reagentIndexMap.TryGetValue(args.Id, out var reagentId))
            {
                OnSelectReagent?.Invoke(reagentId);
            }
        };
    }

    private void UpdateToggleButton()
        => ToggleStatusButton.Text = _enabled
            ? Loc.GetString("plumbing-synthesizer-enabled")
            : Loc.GetString("plumbing-synthesizer-disabled");

    public void UpdateState(PlumbingSynthesizerBoundUserInterfaceState state)
    {
        _enabled = state.Enabled;
        UpdateToggleButton();

        BatteryBar.Value = state.BatteryCharge;

        _reagentIndexMap.Clear();
        ReagentSelector.Clear();

        ReagentSelector.AddItem(Loc.GetString("plumbing-synthesizer-none"), 0);

        var sortedReagents = new List<string>(state.GeneratableReagents.Keys);
        sortedReagents.Sort();

        var idx = 1;
        var selectedIdx = 0;
        foreach (var reagentId in sortedReagents)
        {
            var powerDrain = state.GeneratableReagents[reagentId];
            var reagentName = _prototypeManager.TryIndex<ReagentPrototype>(reagentId, out var proto)
                ? proto.LocalizedName
                : reagentId;
            var label = Loc.GetString("plumbing-synthesizer-reagent-entry", ("reagent", reagentName), ("power", powerDrain.ToString("F1")));
            ReagentSelector.AddItem(label, idx);
            _reagentIndexMap[idx] = reagentId;

            if (state.SelectedReagent == reagentId)
                selectedIdx = idx;

            idx++;
        }

        ReagentSelector.SelectId(selectedIdx);
    }
}
