using System.IO;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Sunset.CustomLawboard;
using Content.Shared.FixedPoint;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Markdown;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using YamlDotNet.RepresentationModel;

namespace Content.Client._Sunset.CustomLawboard;

[GenerateTypedNameReferences]
public sealed partial class LawboardSiliconLawUi : FancyWindow
{
    [Dependency] private readonly IFileDialogManager _dialogManager = default!;
    [Dependency] private readonly ILogManager _logMan = default!;
    [Dependency] private readonly ISerializationManager _serMan = default!;

    private List<SiliconLaw> _laws = new();
    private readonly ISawmill _sawmill;

    public event Action<List<SiliconLaw>, bool>? LawsChangedEvent;

    public LawboardSiliconLawUi()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logMan.GetSawmill("customlawboard-ui");

        NewLawButton.OnPressed += _ => AddNewLaw();
        Save.OnPressed += _ => SaveLaws();

        Import.OnPressed += _ => ImportLaws();
        Export.OnPressed += _ => ExportLaws();
    }

    private void AddNewLaw()
    {
        var newLaw = new SiliconLaw { Order = FixedPoint2.New(_laws.Count + 1) };
        _laws.Add(newLaw);
        SetLaws(_laws);
    }

    public void SaveLaws()
    {
        Save.Disabled = true;
        Timer.Spawn(500, () => Save.Disabled = false);

        LawsChangedEvent?.Invoke(_laws, true);
    }

    public void SetLaws(List<SiliconLaw> sLaws)
    {
        _laws = sLaws;
        LawContainer.RemoveAllChildren();

        foreach (var law in sLaws.OrderBy(l => l.Order))
        {
            var lawControl = new LawboardSiliconLawContainer();
            lawControl.SetLaw(law);
            lawControl.MoveLawDown += MoveLawDown;
            lawControl.MoveLawUp += MoveLawUp;
            lawControl.DeleteAction += DeleteLaw;
            lawControl.ChangeLawEvent += ChangeLaw;

            LawContainer.AddChild(lawControl);
        }

        NewLawButton.Disabled = sLaws.Count >= SharedCustomLawboardSystem.MaxLaws;
    }

    public void DeleteLaw(SiliconLaw law)
    {
        _laws.Remove(law);
        SetLaws(_laws);
    }

    public void MoveLawDown(SiliconLaw law)
    {
        var index = _laws.IndexOf(law);
        if (index == -1)
            return;

        _laws[index].Order += FixedPoint2.New(1);
        SetLaws(_laws);
    }

    public void MoveLawUp(SiliconLaw law)
    {
        var index = _laws.IndexOf(law);
        if (index == -1)
            return;

        _laws[index].Order += FixedPoint2.New(-1);
        SetLaws(_laws);
    }

    public void ChangeLaw(SiliconLaw law)
    {
        var index = _laws.IndexOf(law);
        if (index == -1)
            return;

        if (law.LawString.Length > SharedCustomLawboardSystem.MaxLawLength)
            law.LawString = law.LawString[..SharedCustomLawboardSystem.MaxLawLength];

        _laws[index].LawString = law.LawString;
    }

    private async void ExportLaws()
    {
        var lawset = SharedCustomLawboardSystem.CreateLawset(_laws);
        if (await _dialogManager.SaveFile(new FileDialogFilters(new FileDialogFilters.Group("yml"))) is not { } file)
            return;

        try
        {
            var node = _serMan.WriteValue(lawset.GetType(), lawset);
            await using var writer = new StreamWriter(file.fileStream);
            node.Write(writer);
        }
        catch (Exception e)
        {
            _sawmill.Error($"Error when exporting lawboard: {e}");
        }
        finally
        {
            await file.fileStream.DisposeAsync();
        }
    }

    private async void ImportLaws()
    {
        if (await _dialogManager.OpenFile(new FileDialogFilters(new FileDialogFilters.Group("yml"))) is not { } file)
            return;

        try
        {
            using var reader = new StreamReader(file, EncodingHelpers.UTF8);
            var yamlStream = new YamlStream();
            yamlStream.Load(reader);
            var root = yamlStream.Documents[0].RootNode;
            var lawset = _serMan.Read<SiliconLawset>(root.ToDataNode(), notNullableOverride: true);

            _laws = SharedCustomLawboardSystem.SanitizeLaws(lawset.Laws);
            SetLaws(_laws);
            LawsChangedEvent?.Invoke(_laws, true);
        }
        catch (Exception e)
        {
            _sawmill.Error($"Error when importing lawboard: {e}");
        }
    }
}
