using Content.Shared.Players.PlayTimeTracking;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.Tabs.PlaytimeTab;

// 🌇Sunset🌇 - "Перенос времени" admin menu tab, see PlaytimeTab.xaml for the why.
[GenerateTypedNameReferences]
public sealed partial class PlaytimeTab : Control
{
    [Dependency] private readonly IClientConsoleHost _console = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    private readonly List<string> _trackerIds = new();

    // 🌇Sunset🌇 - the underlying playtime_* console commands only take a raw minute count, so the
    // unit picker just converts to minutes client-side before building the command. Months use a
    // flat 30-day approximation, same as most admin tooling that doesn't need calendar precision.
    private static readonly (string Loc, int Minutes)[] Units =
    {
        ("playtime-tab-unit-minutes", 1),
        ("playtime-tab-unit-hours", 60),
        ("playtime-tab-unit-days", 60 * 24),
        ("playtime-tab-unit-months", 60 * 24 * 30),
    };

    /// <summary>
    /// Initializes the playtime management tab and wires its controls to playtime commands.
    /// </summary>
    public PlaytimeTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateTrackers();
        PopulateUnits();

        TrackerOption.OnItemSelected += args => TrackerOption.SelectId(args.Id);
        UnitOption.OnItemSelected += args => UnitOption.SelectId(args.Id);

        GetButton.OnPressed += _ => RunCommand(getOverall: "playtime_getoverall", getRole: "playtime_getrole");
        AddButton.OnPressed += _ => RunCommand(getOverall: "playtime_addoverall", getRole: "playtime_addrole", needsMinutes: true);
        SetButton.OnPressed += _ => RunCommand(getOverall: "playtime_setoverall", getRole: "playtime_setrole", needsMinutes: true);
    }

    private void PopulateUnits()
    {
        for (var i = 0; i < Units.Length; i++)
        {
            UnitOption.AddItem(Loc.GetString(Units[i].Loc), i);
        }

        UnitOption.SelectId(0);
    }

    // 🌇Sunset🌇 - list every registered playtime tracker instead of making admins type the id from
    // memory. Most trackers are jobs, whose own displayed name is far more recognisable than the
    // tracker id (e.g. "JobBartender") - so where a job references a tracker, show the job's name.
    private void PopulateTrackers()
    {
        var jobNameByTracker = new Dictionary<string, string>();
        foreach (var job in _prototypes.EnumeratePrototypes<JobPrototype>())
        {
            if (!string.IsNullOrEmpty(job.PlayTimeTracker))
                jobNameByTracker[job.PlayTimeTracker] = job.LocalizedName;
        }

        var entries = new List<(string Id, string Label)>();
        foreach (var tracker in _prototypes.EnumeratePrototypes<PlayTimeTrackerPrototype>())
        {
            if (jobNameByTracker.TryGetValue(tracker.ID, out var jobName))
                entries.Add((tracker.ID, $"{jobName} ({tracker.ID})"));
            // 🌇Sunset🌇 - non-job trackers (mostly antags) can declare their own localized name via
            // the playTimeTracker prototype's `name:` field; fall back to it instead of the bare id
            // so the dropdown doesn't just show raw tracker ids like "AntagVampire".
            else if (tracker.Name.Id != "generic-unknown")
                entries.Add((tracker.ID, $"{tracker.LocalizedName} ({tracker.ID})"));
            else
                entries.Add((tracker.ID, tracker.ID));
        }

        entries.Sort((a, b) =>
        {
            // Pin Overall first, it's by far the most commonly used tracker.
            if (a.Id == PlayTimeTrackingShared.TrackerOverall)
                return b.Id == PlayTimeTrackingShared.TrackerOverall ? 0 : -1;
            if (b.Id == PlayTimeTrackingShared.TrackerOverall)
                return 1;

            return string.Compare(a.Label, b.Label, StringComparison.CurrentCultureIgnoreCase);
        });

        foreach (var (id, label) in entries)
        {
            _trackerIds.Add(id);
            TrackerOption.AddItem(label, _trackerIds.Count - 1);
        }

        TrackerOption.SelectId(0);
    }

    private string GetSelectedTracker()
    {
        var id = TrackerOption.SelectedId;
        return id >= 0 && id < _trackerIds.Count ? _trackerIds[id] : PlayTimeTrackingShared.TrackerOverall.Id;
    }

    private void RunCommand(string getOverall, string getRole, bool needsMinutes = false)
    {
        var username = UsernameInput.Text.Trim();
        if (username.Length == 0)
            return;

        var tracker = GetSelectedTracker();
        var isOverall = tracker == PlayTimeTrackingShared.TrackerOverall;

        if (!needsMinutes)
        {
            _console.ExecuteCommand(isOverall
                ? $"{getOverall} \"{username}\""
                : $"{getRole} \"{username}\" \"{tracker}\"");
            return;
        }

        if (!int.TryParse(MinutesInput.Text, out var amount))
            return;

        var unitId = UnitOption.SelectedId;
        var multiplier = unitId >= 0 && unitId < Units.Length ? Units[unitId].Minutes : 1;
        var minutes = amount * multiplier;

        _console.ExecuteCommand(isOverall
            ? $"{getOverall} \"{username}\" {minutes}"
            : $"{getRole} \"{username}\" \"{tracker}\" {minutes}");
    }
}
