using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunset.CustomEmotes;

[GenerateTypedNameReferences]
public sealed partial class CustomEmotesWindow : DefaultWindow
{
    private CustomEmotesUIController? _controller;
    private int _editingIndex = -1;

    public CustomEmotesWindow()
    {
        RobustXamlLoader.Load(this);

        NameEdit.OnTextChanged += _ => UpdateSaveButton();
        EmoteTextEdit.OnTextChanged += _ => UpdateSaveButton();
        SaveButton.OnPressed += _ => OnSavePressed();
        CancelEditButton.OnPressed += _ => ResetForm();

        UpdateSaveButton();
    }

    public void SetController(CustomEmotesUIController controller)
    {
        _controller = controller;
        Refresh();
    }

    public void Refresh()
    {
        EntriesContainer.RemoveAllChildren();

        if (_controller == null)
            return;

        var entries = _controller.Entries;
        EmptyLabel.Visible = entries.Count == 0;

        for (var i = 0; i < entries.Count; i++)
        {
            EntriesContainer.AddChild(MakeRow(i, entries[i]));
        }
    }

    private Control MakeRow(int index, CustomEmoteEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 0, 4),
        };

        row.AddChild(new Label
        {
            Text = entry.Name,
            HorizontalExpand = true,
            ClipText = true,
            ToolTip = entry.Text,
        });

        var useButton = new Button { Text = Loc.GetString("custom-emotes-window-use") };
        useButton.OnPressed += _ => _controller?.FireEntry(entry);
        row.AddChild(useButton);

        var editButton = new Button { Text = Loc.GetString("custom-emotes-window-edit"), Margin = new Thickness(4, 0, 0, 0) };
        editButton.OnPressed += _ => BeginEdit(index, entry);
        row.AddChild(editButton);

        var deleteButton = new Button { Text = Loc.GetString("custom-emotes-window-delete"), Margin = new Thickness(4, 0, 0, 0) };
        deleteButton.OnPressed += _ =>
        {
            _controller?.RemoveEntry(index);
            if (_editingIndex == index)
                ResetForm();
            Refresh();
        };
        row.AddChild(deleteButton);

        return row;
    }

    private void BeginEdit(int index, CustomEmoteEntry entry)
    {
        _editingIndex = index;
        NameEdit.Text = entry.Name;
        EmoteTextEdit.Text = entry.Text;
        CancelEditButton.Visible = true;
        SaveButton.Text = Loc.GetString("custom-emotes-window-update");
        UpdateSaveButton();
    }

    private void ResetForm()
    {
        _editingIndex = -1;
        NameEdit.Text = string.Empty;
        EmoteTextEdit.Text = string.Empty;
        CancelEditButton.Visible = false;
        SaveButton.Text = Loc.GetString("custom-emotes-window-save");
        UpdateSaveButton();
    }

    private void OnSavePressed()
    {
        var name = NameEdit.Text.Trim();
        var text = EmoteTextEdit.Text.Trim();

        if (name.Length == 0 || text.Length == 0)
            return;

        if (_editingIndex == -1)
            _controller?.AddEntry(name, text);
        else
            _controller?.UpdateEntry(_editingIndex, name, text);

        ResetForm();
        Refresh();
    }

    private void UpdateSaveButton()
    {
        SaveButton.Disabled = NameEdit.Text.Trim().Length == 0 || EmoteTextEdit.Text.Trim().Length == 0;
    }
}
