// SPDX-FileCopyrightText: 2026 sunset-station contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client.Message;
using Content.Shared._Sunset.Genetics;
using Content.Shared._Sunset.Genetics.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunset.Genetics.UI;

[GenerateTypedNameReferences]
public sealed partial class DnaModifierConsoleWindow : DefaultWindow
{
    // Medical console palette (matches the XAML): white cards on a light blue backdrop,
    // dark navy body text, medical blue accents.
    private const string TextColor = "#173B52";
    private const string AccentColor = "#1E7FA6";
    private const string ActiveColor = "#2E8B57";
    private const string MutedColor = "#5E7E92";
    private static readonly Color CardColor = Color.FromHex("#FFFFFF");
    private static readonly Color CardBorderColor = Color.FromHex("#A8CEE2");

    public event Action<GenomeCategory, int, int>? OnRadiate;
    public event Action<GenomeCategory>? OnPulse;
    public event Action? OnEject;
    public event Action<DnaBufferAction, int>? OnBuffer;
    public event Action<string>? OnPrintActivator;

    private int _subBlock = 2; // low subblock by default

    private readonly Dictionary<(GenomeCategory Category, int Block), Label> _valueLabels = new();
    private readonly Dictionary<int, Label> _bufferLabels = new();

    public DnaModifierConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(0, Loc.GetString("dna-modifier-console-tab-overview"));
        Tabs.SetTabTitle(1, Loc.GetString("dna-modifier-console-tab-identifiers"));
        Tabs.SetTabTitle(2, Loc.GetString("dna-modifier-console-tab-structural"));
        Tabs.SetTabTitle(3, Loc.GetString("dna-modifier-console-tab-discovered"));

        EjectButton.OnPressed += _ => OnEject?.Invoke();
        PulseUiButton.OnPressed += _ => OnPulse?.Invoke(GenomeCategory.Ui);
        PulseSeButton.OnPressed += _ => OnPulse?.Invoke(GenomeCategory.Se);

        // The subblock selector lives on both editing tabs (Identifiers and Structural); the two
        // button rows share one target so switching tabs keeps the aim.
        foreach (var button in SubBlockButtons())
            button.ToggleMode = true;

        UiHighButton.OnPressed += _ => SetSubBlock(0);
        UiMidButton.OnPressed += _ => SetSubBlock(1);
        UiLowButton.OnPressed += _ => SetSubBlock(2);
        SeHighButton.OnPressed += _ => SetSubBlock(0);
        SeMidButton.OnPressed += _ => SetSubBlock(1);
        SeLowButton.OnPressed += _ => SetSubBlock(2);
        SetSubBlock(2);

        BuildRows();
    }

    private IEnumerable<Button> SubBlockButtons()
    {
        yield return UiHighButton;
        yield return UiMidButton;
        yield return UiLowButton;
        yield return SeHighButton;
        yield return SeMidButton;
        yield return SeLowButton;
    }

    private void SetSubBlock(int pos)
    {
        _subBlock = pos;
        UiHighButton.Pressed = pos == 0;
        UiMidButton.Pressed = pos == 1;
        UiLowButton.Pressed = pos == 2;
        SeHighButton.Pressed = pos == 0;
        SeMidButton.Pressed = pos == 1;
        SeLowButton.Pressed = pos == 2;
    }

    private void BuildRows()
    {
        for (var slot = 0; slot < 3; slot++)
            AddBufferRow(slot);

        // Create a list of all UI blocks to display in grid
        var uiBlocks = new List<(GenomeCategory, int, string)>
        {
            (GenomeCategory.Ui, GenomeComponent.BlockSkinR, Loc.GetString("dna-modifier-console-block-skin-r")),
            (GenomeCategory.Ui, GenomeComponent.BlockSkinG, Loc.GetString("dna-modifier-console-block-skin-g")),
            (GenomeCategory.Ui, GenomeComponent.BlockSkinB, Loc.GetString("dna-modifier-console-block-skin-b")),
            (GenomeCategory.Ui, GenomeComponent.BlockEyeR, Loc.GetString("dna-modifier-console-block-eye-r")),
            (GenomeCategory.Ui, GenomeComponent.BlockEyeG, Loc.GetString("dna-modifier-console-block-eye-g")),
            (GenomeCategory.Ui, GenomeComponent.BlockEyeB, Loc.GetString("dna-modifier-console-block-eye-b")),
            (GenomeCategory.Ui, GenomeComponent.BlockSex, Loc.GetString("dna-modifier-console-block-sex"))
        };

        AddGridRows(UiBlockRows, uiBlocks);

        // Create a list of all SE blocks to display in grid
        var seBlocks = new List<(GenomeCategory, int, string)>();
        for (var i = 1; i < GenomeComponent.SeBlockCount; i++)
            seBlocks.Add((GenomeCategory.Se, i, Loc.GetString("dna-modifier-console-block-se", ("index", i))));

        AddGridRows(SeBlockRows, seBlocks);
    }

    private void AddGridRows(BoxContainer target, List<(GenomeCategory category, int block, string label)> blocks)
    {
        const int cellsPerColumn = 6;

        // Calculate number of columns needed
        var columnCount = (int)Math.Ceiling((double)blocks.Count / cellsPerColumn);

        // Create horizontal container for all columns
        var columnsContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        // Create each column
        for (var col = 0; col < columnCount; col++)
        {
            var columnContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            // Add cells to this column (top to bottom)
            var startIdx = col * cellsPerColumn;
            var endIdx = Math.Min(startIdx + cellsPerColumn, blocks.Count);

            for (var i = startIdx; i < endIdx; i++)
            {
                var (category, block, label) = blocks[i];
                AddCellToColumn(columnContainer, category, block, label);
            }

            columnsContainer.AddChild(columnContainer);
        }

        target.AddChild(columnsContainer);
    }

    private void AddCellToColumn(BoxContainer columnContainer, GenomeCategory category, int block, string label)
    {
        var cellContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(2, 2, 2, 2),
        };

        var labelControl = new Label
        {
            Text = label,
            MinSize = new Vector2(80, 0),
            FontColorOverride = Color.FromHex(TextColor),
        };
        cellContainer.AddChild(labelControl);

        var value = new Label
        {
            Text = "000",
            MinSize = new Vector2(36, 0),
            HorizontalAlignment = Control.HAlignment.Center,
            FontColorOverride = Color.FromHex(AccentColor),
        };

        // Paradise-style: no precise editing, just a radiation pulse aimed at this block's
        // currently selected subblock - the outcome is up to the beam.
        var irradiate = new Button
        {
            Text = Loc.GetString("dna-modifier-console-irradiate"),
            MinSize = new Vector2(24, 0),
        };
        irradiate.OnPressed += _ => OnRadiate?.Invoke(category, block, _subBlock);

        cellContainer.AddChild(value);
        cellContainer.AddChild(irradiate);

        columnContainer.AddChild(cellContainer);

        _valueLabels[(category, block)] = value;
    }

    private void AddBufferRow(int slot)
    {
        // Each buffer is its own little white card, like a sample tray in a medical console.
        var card = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = CardColor,
                BorderColor = CardBorderColor,
                BorderThickness = new Thickness(1),
            },
            Margin = new Thickness(0, 2, 0, 2),
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(6, 4, 6, 4),
        };

        var status = new Label
        {
            Text = Loc.GetString("dna-modifier-console-buffer-empty", ("slot", slot + 1)),
            MinSize = new Vector2(120, 0),
            FontColorOverride = Color.FromHex(TextColor),
        };
        row.AddChild(status);

        AddBufferButton(row, "dna-modifier-console-buffer-save-se", DnaBufferAction.SaveSe, slot);
        AddBufferButton(row, "dna-modifier-console-buffer-save-ui", DnaBufferAction.SaveUi, slot);
        AddBufferButton(row, "dna-modifier-console-buffer-apply", DnaBufferAction.Apply, slot);
        AddBufferButton(row, "dna-modifier-console-buffer-injector", DnaBufferAction.Injector, slot);
        AddBufferButton(row, "dna-modifier-console-buffer-clear", DnaBufferAction.Clear, slot);

        card.AddChild(row);
        BufferRows.AddChild(card);
        _bufferLabels[slot] = status;
    }

    private void AddBufferButton(BoxContainer row, string locKey, DnaBufferAction action, int slot)
    {
        var button = new Button { Text = Loc.GetString(locKey) };
        button.OnPressed += _ => OnBuffer?.Invoke(action, slot);
        row.AddChild(button);
    }

    public void Populate(DnaModifierConsoleBoundUserInterfaceState state)
    {
        if (!state.MachineConnected)
            StatusLabel.Text = Loc.GetString("dna-modifier-console-no-machine");
        else if (!state.MachineInRange)
            StatusLabel.Text = Loc.GetString("dna-modifier-console-machine-far");
        else if (!state.HasOccupant)
            StatusLabel.Text = Loc.GetString("dna-modifier-console-no-occupant-status");
        else
            StatusLabel.Text = string.Empty;

        OccupantLabel.Text = state.HasOccupant
            ? Loc.GetString("dna-modifier-console-occupant", ("name", state.OccupantName))
            : Loc.GetString("dna-modifier-console-no-occupant");

        EjectButton.Disabled = !state.HasOccupant;

        InstabilityLabel.Text = Loc.GetString("dna-modifier-console-instability", ("value", (int) state.Instability));
        InstabilityBar.Value = Math.Clamp(state.Instability, 0f, 100f);

        // Bar color follows the server's instability thresholds (GeneticsSystem.Instability.cs:
        // burns at 25, deformation at 40, lethal at 70).
        var barColor = state.Instability switch
        {
            >= 70f => "#C0392B", // lethal - red
            >= 40f => "#E67E22", // deformation - orange
            >= 25f => "#D4AC0D", // burns - yellow
            _ => "#2E86AB", // safe - medical blue
        };
        InstabilityBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex(barColor) };

        // RichTextLabel takes its color from the (dark) theme, which is unreadable on the white
        // card - recolor through markup instead.
        MutationsLabel.SetMarkup(state.ActiveMutations.Count == 0
            ? $"[color={MutedColor}]{Loc.GetString("dna-modifier-console-no-mutations")}[/color]"
            : $"[color={TextColor}]{string.Join(", ", state.ActiveMutations)}[/color]");

        foreach (var ((category, block), label) in _valueLabels)
        {
            var list = category switch
            {
                GenomeCategory.Ui => state.Ui,
                GenomeCategory.Ue => state.Ue,
                _ => state.Se,
            };

            var value = block >= 0 && block < list.Count ? list[block] : 0;
            label.Text = value.ToString("X3");
        }

        foreach (var (slot, label) in _bufferLabels)
        {
            var filled = slot < state.BufferFilled.Count && state.BufferFilled[slot];
            label.Text = filled
                ? Loc.GetString("dna-modifier-console-buffer-full", ("slot", slot + 1))
                : Loc.GetString("dna-modifier-console-buffer-empty", ("slot", slot + 1));
        }

        PopulateDiscovered(state);
    }

    private void PopulateDiscovered(DnaModifierConsoleBoundUserInterfaceState state)
    {
        DiscoveredContainer.RemoveAllChildren();

        if (state.DiscoveredMutations.Count == 0)
        {
            DiscoveredContainer.AddChild(new Label
            {
                Text = Loc.GetString("dna-modifier-console-no-discovered"),
                FontColorOverride = Color.FromHex(MutedColor),
            });
            return;
        }

        foreach (var info in state.DiscoveredMutations)
        {
            // One white card per researched mutation: name (green when active on the occupant),
            // its description in muted blue-grey underneath, print button on the right.
            var card = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = CardColor,
                    BorderColor = CardBorderColor,
                    BorderThickness = new Thickness(1),
                },
                Margin = new Thickness(0, 2, 0, 2),
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(8, 6, 8, 6),
            };

            var textColumn = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            textColumn.AddChild(new Label
            {
                Text = info.Name,
                FontColorOverride = Color.FromHex(info.ActiveOnOccupant ? ActiveColor : TextColor),
            });

            if (!string.IsNullOrWhiteSpace(info.Description))
            {
                var description = new RichTextLabel { HorizontalExpand = true };
                description.SetMarkup($"[color={MutedColor}]{info.Description}[/color]");
                textColumn.AddChild(description);
            }

            row.AddChild(textColumn);

            var print = new Button
            {
                Text = Loc.GetString("dna-modifier-console-print-activator"),
                VerticalAlignment = VAlignment.Center,
            };
            print.OnPressed += _ => OnPrintActivator?.Invoke(info.Id);
            row.AddChild(print);

            card.AddChild(row);
            DiscoveredContainer.AddChild(card);
        }
    }
}
