// SPDX-FileCopyrightText: 2026 sunset-station contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Shared._Sunset.Genetics;
using Content.Shared._Sunset.Genetics.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunset.Genetics.UI;

[GenerateTypedNameReferences]
public sealed partial class DnaModifierConsoleWindow : DefaultWindow
{
    public event Action<GenomeCategory, int, int, int>? OnRadiate;
    public event Action<GenomeCategory>? OnPulse;
    public event Action? OnEject;
    public event Action<DnaBufferAction, int>? OnBuffer;
    public event Action<string>? OnPrintActivator;

    private int _subBlock = 2; // low subblock by default

    private readonly Dictionary<(GenomeCategory Category, int Block), Label> _valueLabels = new();
    private readonly Dictionary<int, Label> _bufferLabels = new();

    public DnaModifierConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        EjectButton.OnPressed += _ => OnEject?.Invoke();
        PulseUiButton.OnPressed += _ => OnPulse?.Invoke(GenomeCategory.Ui);
        PulseSeButton.OnPressed += _ => OnPulse?.Invoke(GenomeCategory.Se);

        HighButton.ToggleMode = true;
        MidButton.ToggleMode = true;
        LowButton.ToggleMode = true;
        HighButton.OnPressed += _ => SetSubBlock(0);
        MidButton.OnPressed += _ => SetSubBlock(1);
        LowButton.OnPressed += _ => SetSubBlock(2);
        SetSubBlock(2);

        BuildRows();
    }

    private void SetSubBlock(int pos)
    {
        _subBlock = pos;
        HighButton.Pressed = pos == 0;
        MidButton.Pressed = pos == 1;
        LowButton.Pressed = pos == 2;
    }

    private void BuildRows()
    {
        AddHeader(Loc.GetString("dna-modifier-console-header-buffers"));
        for (var slot = 0; slot < 3; slot++)
            AddBufferRow(slot);

        AddHeader(Loc.GetString("dna-modifier-console-header-identifiers"));

        // Create a list of all UI blocks to display in grid
        var uiBlocks = new List<(GenomeCategory, int, string)>
        {
            (GenomeCategory.Ui, GenomeComponent.BlockSkinR, Loc.GetString("dna-modifier-console-block-skin-r")),
            (GenomeCategory.Ui, GenomeComponent.BlockSkinG, Loc.GetString("dna-modifier-console-block-skin-g")),
            (GenomeCategory.Ui, GenomeComponent.BlockSkinB, Loc.GetString("dna-modifier-console-block-skin-b")),
            (GenomeCategory.Ui, GenomeComponent.BlockEyeR, Loc.GetString("dna-modifier-console-block-eye-r")),
            (GenomeCategory.Ui, GenomeComponent.BlockEyeG, Loc.GetString("dna-modifier-console-block-eye-g")),
            (GenomeCategory.Ui, GenomeComponent.BlockEyeB, Loc.GetString("dna-modifier-console-block-eye-b")),
            (GenomeCategory.Ui, GenomeComponent.BlockSex, Loc.GetString("dna-modifier-console-block-sex"))
        };

        AddGridRows(uiBlocks);

        AddHeader(Loc.GetString("dna-modifier-console-header-structural"));

        // Create a list of all SE blocks to display in grid
        var seBlocks = new List<(GenomeCategory, int, string)>();
        for (var i = 1; i < GenomeComponent.SeBlockCount; i++)
            seBlocks.Add((GenomeCategory.Se, i, Loc.GetString("dna-modifier-console-block-se", ("index", i))));

        AddGridRows(seBlocks);
    }

    private void AddGridRows(List<(GenomeCategory category, int block, string label)> blocks)
    {
        const int cellsPerColumn = 6;

        // Calculate number of columns needed
        var columnCount = (int)Math.Ceiling((double)blocks.Count / cellsPerColumn);

        // Create horizontal container for all columns
        var columnsContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        // Create each column
        for (var col = 0; col < columnCount; col++)
        {
            var columnContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            // Add cells to this column (top to bottom)
            var startIdx = col * cellsPerColumn;
            var endIdx = Math.Min(startIdx + cellsPerColumn, blocks.Count);

            for (var i = startIdx; i < endIdx; i++)
            {
                var (category, block, label) = blocks[i];
                AddCellToColumn(columnContainer, category, block, label);
            }

            columnsContainer.AddChild(columnContainer);
        }

        BlockRows.AddChild(columnsContainer);
    }

    private void AddCellToColumn(BoxContainer columnContainer, GenomeCategory category, int block, string label)
    {
        var cellContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(2, 2, 2, 2),
        };

        var labelControl = new Label
        {
            Text = label,
            MinSize = new Vector2(80, 0),
        };
        cellContainer.AddChild(labelControl);

        var minus = new Button { Text = "-", MinSize = new Vector2(24, 0) };
        var value = new Label { Text = "000", MinSize = new Vector2(36, 0), HorizontalAlignment = Control.HAlignment.Center };
        var plus = new Button { Text = "+", MinSize = new Vector2(24, 0) };

        minus.OnPressed += _ => OnRadiate?.Invoke(category, block, _subBlock, -1);
        plus.OnPressed += _ => OnRadiate?.Invoke(category, block, _subBlock, 1);

        cellContainer.AddChild(minus);
        cellContainer.AddChild(value);
        cellContainer.AddChild(plus);

        columnContainer.AddChild(cellContainer);

        _valueLabels[(category, block)] = value;
    }

    private void AddHeader(string text)
    {
        BlockRows.AddChild(new Label
        {
            Text = text,
            StyleClasses = { "LabelKeyText" },
            Margin = new Thickness(0, 6, 0, 2),
        });
    }

    private void AddBufferRow(int slot)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var status = new Label
        {
            Text = Loc.GetString("dna-modifier-console-buffer-empty", ("slot", slot + 1)),
            MinSize = new Vector2(120, 0),
        };
        row.AddChild(status);

        AddBufferButton(row, "dna-modifier-console-buffer-save-se", DnaBufferAction.SaveSe, slot);
        AddBufferButton(row, "dna-modifier-console-buffer-save-ui", DnaBufferAction.SaveUi, slot);
        AddBufferButton(row, "dna-modifier-console-buffer-apply", DnaBufferAction.Apply, slot);
        AddBufferButton(row, "dna-modifier-console-buffer-injector", DnaBufferAction.Injector, slot);
        AddBufferButton(row, "dna-modifier-console-buffer-clear", DnaBufferAction.Clear, slot);

        BlockRows.AddChild(row);
        _bufferLabels[slot] = status;
    }

    private void AddBufferButton(BoxContainer row, string locKey, DnaBufferAction action, int slot)
    {
        var button = new Button { Text = Loc.GetString(locKey) };
        button.OnPressed += _ => OnBuffer?.Invoke(action, slot);
        row.AddChild(button);
    }

    public void Populate(DnaModifierConsoleBoundUserInterfaceState state)
    {
        if (!state.MachineConnected)
            StatusLabel.Text = Loc.GetString("dna-modifier-console-no-machine");
        else if (!state.MachineInRange)
            StatusLabel.Text = Loc.GetString("dna-modifier-console-machine-far");
        else if (!state.HasOccupant)
            StatusLabel.Text = Loc.GetString("dna-modifier-console-no-occupant-status");
        else
            StatusLabel.Text = string.Empty;

        OccupantLabel.Text = state.HasOccupant
            ? Loc.GetString("dna-modifier-console-occupant", ("name", state.OccupantName))
            : Loc.GetString("dna-modifier-console-no-occupant");

        EjectButton.Disabled = !state.HasOccupant;

        InstabilityLabel.Text = Loc.GetString("dna-modifier-console-instability", ("value", (int) state.Instability));
        MutationsLabel.SetMessage(state.ActiveMutations.Count == 0
            ? Loc.GetString("dna-modifier-console-no-mutations")
            : string.Join(", ", state.ActiveMutations));

        foreach (var ((category, block), label) in _valueLabels)
        {
            var list = category switch
            {
                GenomeCategory.Ui => state.Ui,
                GenomeCategory.Ue => state.Ue,
                _ => state.Se,
            };

            var value = block >= 0 && block < list.Count ? list[block] : 0;
            label.Text = value.ToString("X3");
        }

        foreach (var (slot, label) in _bufferLabels)
        {
            var filled = slot < state.BufferFilled.Count && state.BufferFilled[slot];
            label.Text = filled
                ? Loc.GetString("dna-modifier-console-buffer-full", ("slot", slot + 1))
                : Loc.GetString("dna-modifier-console-buffer-empty", ("slot", slot + 1));
        }

        PopulateDiscovered(state);
    }

    private void PopulateDiscovered(DnaModifierConsoleBoundUserInterfaceState state)
    {
        DiscoveredContainer.RemoveAllChildren();

        if (state.DiscoveredMutations.Count == 0)
        {
            DiscoveredContainer.AddChild(new Label { Text = Loc.GetString("dna-modifier-console-no-discovered") });
            return;
        }

        foreach (var info in state.DiscoveredMutations)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var name = new Label
            {
                Text = info.Name,
                MinSize = new Vector2(140, 0),
                ToolTip = info.Description,
            };
            if (info.ActiveOnOccupant)
                name.FontColorOverride = Color.FromHex("#5fbf5f");
            row.AddChild(name);

            var print = new Button { Text = Loc.GetString("dna-modifier-console-print-activator") };
            print.OnPressed += _ => OnPrintActivator?.Invoke(info.Id);
            row.AddChild(print);

            DiscoveredContainer.AddChild(row);
        }
    }
}
