using System.Linq;
using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Sunset.Boombox;

/// <summary>
/// 🌇Sunset🌇 - Boombox-only reskin of the stationary Jukebox's menu: a distinct neon theme, a
/// search box to filter the (much longer) boombox playlist, per-track durations in the list, and
/// a repeat toggle. Deliberately a standalone class (not inheriting JukeboxMenu, which is sealed
/// and has its own fixed XAML) rather than touching the shared jukebox machine UI.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class BoomboxMenu : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    private AudioSystem _audioSystem;

    private bool _playState;
    private bool _loopState;

    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<ProtoId<JukeboxPrototype>>? OnSongSelected;
    public event Action<float>? SetTime;
    public event Action<float>? OnVolumeChanged;
    public event Action<bool>? OnLoopChanged;

    private EntityUid? _audio;
    private float _lockTimer;

    /// <summary>
    /// Full unfiltered playlist, cached so the search box can re-filter without re-querying the BUI.
    /// </summary>
    private List<JukeboxPrototype> _allSongs = new();

    public BoomboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        MusicList.OnItemSelected += args =>
        {
            var entry = MusicList[args.ItemIndex];

            if (entry.Metadata is not string juke)
                return;

            OnSongSelected?.Invoke(juke);
        };

        PlayButton.OnPressed += _ =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };

        StopButton.OnPressed += _ =>
        {
            OnStopPressed?.Invoke();
        };

        RepeatButton.OnToggled += args =>
        {
            SetLoop(args.Pressed);
            OnLoopChanged?.Invoke(args.Pressed);
        };

        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;

        VolumeSlider.OnReleased += _ =>
        {
            OnVolumeChanged?.Invoke(VolumeSlider.Value);
        };

        SearchBox.OnTextChanged += _ => Refilter();

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio), force: true);
    }

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    /// <summary>
    /// Re-populates the list of jukebox prototypes available, sorted alphabetically for easier
    /// browsing, and re-applies whatever search filter is currently typed in.
    /// </summary>
    public void Populate(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        _allSongs = jukeboxProtos.OrderBy(s => s.Name).ToList();
        Refilter();
    }

    private void Refilter()
    {
        var filter = SearchBox.Text;

        MusicList.Clear();

        var shown = string.IsNullOrWhiteSpace(filter)
            ? _allSongs
            : _allSongs.Where(s => s.Name.Contains(filter, StringComparison.CurrentCultureIgnoreCase)).ToList();

        foreach (var entry in shown)
        {
            // No per-track duration here: the client can only get a length by fully decoding the
            // file, and doing that for the whole playlist froze the game for seconds on open.
            MusicList.AddItem(entry.Name, metadata: entry.ID);
        }

        TrackCountLabel.Text = Loc.GetString("boombox-menu-track-count", ("count", shown.Count), ("total", _allSongs.Count));
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;

        PlayButton.Text = playing
            ? Loc.GetString("jukebox-menu-buttonpause")
            : Loc.GetString("jukebox-menu-buttonplay");
    }

    public void SetSelectedSong(string name, float length)
    {
        SetSelectedSongText(name);
        PlaybackSlider.MaxValue = length;
        PlaybackSlider.SetValueWithoutEvent(0);
    }

    public void SetVolume(float volume)
    {
        VolumeSlider.SetValueWithoutEvent(volume);
    }

    public void SetLoop(bool loop)
    {
        _loopState = loop;
        RepeatButton.Pressed = loop;
        RepeatButton.Text = Loc.GetString(loop ? "boombox-menu-repeat-on" : "boombox-menu-repeat-off");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
        {
            _lockTimer -= args.DeltaSeconds;
        }

        PlaybackSlider.Disabled = _lockTimer > 0f;

        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            DurationLabel.Text = $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} / {GetCachedAudioLength(audio.FileName):mm\:ss}";
        }
        else
        {
            DurationLabel.Text = "00:00 / 00:00";
        }

        if (!PlaybackSlider.Grabbed)
        {
            if (audio != null || _entManager.TryGetComponent(_audio, out audio))
            {
                PlaybackSlider.SetValueWithoutEvent(audio.PlaybackPosition);
            }
            else
            {
                PlaybackSlider.SetValueWithoutEvent(0f);
            }
        }

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
    }

    // Cache of the last resolved track length, keyed by file - GetAudioLength() re-decodes the
    // resource on every call, and FrameUpdate runs every rendered frame while this window is open,
    // so calling it uncached is a per-frame audio decode (and a per-frame exception for a broken file).
    private string? _cachedLengthFile;
    private TimeSpan _cachedLength;

    private TimeSpan GetCachedAudioLength(string fileName)
    {
        if (fileName == _cachedLengthFile)
            return _cachedLength;

        _cachedLengthFile = fileName;
        _cachedLength = TimeSpan.Zero;

        try
        {
            _cachedLength = _audioSystem.GetAudioLength(fileName);
        }
        catch (Exception e)
        {
            Logger.Error($"Failed to get audio length for boombox playback file '{fileName}': {e}");
        }

        return _cachedLength;
    }

    public void SetSelectedSongText(string? text)
    {
        SongName.Text = string.IsNullOrEmpty(text) ? "---" : text;
    }
}
