using Content.Client.Message;
using Content.Shared._Sunset.Spy.SpyContracts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunset.Spy;

/// <summary>One row on the contract board: name/description/reward and an Accept button.</summary>
[GenerateTypedNameReferences]
public sealed partial class SpyContractControl : BoxContainer
{
    public event Action? OnAccept;

    public SpyContractControl(SpyContractPrototype contract, SpyContractInfo info, bool hasActiveContract)
    {
        RobustXamlLoader.Load(this);

        NameLabel.Text = Loc.GetString(contract.Name);
        DescriptionLabel.SetMarkupPermissive(Loc.GetString(contract.Description));
        RewardLabel.Text = Loc.GetString("spy-uplink-ui-contract-reward", ("amount", info.Reward));

        AcceptButton.OnPressed += _ => OnAccept?.Invoke();
        AcceptButton.Disabled = hasActiveContract;
    }
}
