using System.Linq;
using Content.Client.Message;
using Content.Client.Store.Ui;
using Content.Shared._Sunset.Spy.SpyContracts;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Sunset.Spy;

/// <summary>
/// Red/black-themed window for the Spy Uplink: a Market tab (reuses the vanilla
/// StoreListingControl for individual items so purchase math/discounts/restock timers stay
/// correct) and a Contracts tab (fully custom - see SpyContractControl).
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SpyUplinkMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<ListingDataWithCostModifiers>? OnListingButtonPressed;
    public event Action<string, int>? OnWithdrawAttempt;
    public event Action<ProtoId<SpyContractPrototype>>? OnContractAccepted;
    public event Action? OnContractAbandoned;

    private StoreWithdrawWindow? _withdrawWindow;
    private Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> _balance = new();

    private List<ListingDataWithCostModifiers> _listings = new();
    private ProtoId<StoreCategoryPrototype>? _currentCategory;

    public SpyUplinkMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MarketTabButton.OnButtonDown += _ => SetTab(market: true);
        ContractsTabButton.OnButtonDown += _ => SetTab(market: false);
        WithdrawButton.OnButtonDown += OnWithdrawButtonDown;
        AbandonButton.OnButtonDown += _ => OnContractAbandoned?.Invoke();

        SetTab(market: true);
    }

    private void SetTab(bool market)
    {
        MarketTab.Visible = market;
        ContractsTab.Visible = !market;
    }

    public void UpdateBalance(Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> balance)
    {
        _balance = balance;

        var balanceStr = string.Empty;
        foreach (var (currencyId, amount) in balance)
        {
            var currency = _prototypeManager.Index(currencyId);
            balanceStr += Loc.GetString("store-ui-balance-display", ("amount", amount),
                ("currency", Loc.GetString(currency.DisplayName, ("amount", 1)))) + "\n";
        }

        BalanceInfo.SetMarkup(balanceStr.TrimEnd());

        var canWithdraw = balance.Any(b => _prototypeManager.Index(b.Key).CanWithdraw && b.Value > 0);
        WithdrawButton.Disabled = !canWithdraw;
    }

    // One tab button per store category; only the selected category's items are listed, like the
    // vanilla StoreMenu does it, so the 30-odd items in this shop don't run together into a wall.
    public void UpdateListings(List<ListingDataWithCostModifiers> listings)
    {
        _listings = listings;

        var categories = listings
            .Select(l => l.Categories.FirstOrDefault())
            .Distinct()
            .Where(c => _prototypeManager.HasIndex(c))
            .OrderBy(c => _prototypeManager.Index(c).Priority)
            .ToList();

        if (_currentCategory == null || !categories.Contains(_currentCategory.Value))
            _currentCategory = categories.FirstOrDefault();

        CategoryButtonsContainer.RemoveAllChildren();
        foreach (var category in categories)
        {
            var button = new Button
            {
                Text = Loc.GetString(_prototypeManager.Index(category).Name),
                ToggleMode = true,
                Pressed = category == _currentCategory,
                HorizontalExpand = true,
                StyleClasses = { "OpenBoth" },
            };
            button.OnButtonDown += _ =>
            {
                _currentCategory = category;
                UpdateListings(_listings);
            };
            CategoryButtonsContainer.AddChild(button);
        }

        RefreshMarketListings();
    }

    private void RefreshMarketListings()
    {
        MarketListingsContainer.RemoveAllChildren();

        var spriteSys = _entityManager.System<SpriteSystem>();

        var shown = _listings
            .Where(l => l.Categories.FirstOrDefault() == _currentCategory)
            .OrderBy(l => l.Priority)
            .ThenBy(l => l.Cost.Values.Sum());

        foreach (var listing in shown)
        {
            var hasBalance = listing.CanBuyWith(_balance);

            Texture? texture = null;
            if (listing.Icon != null)
                texture = spriteSys.Frame0(listing.Icon);
            else if (listing.ProductEntity != null)
                texture = spriteSys.GetPrototypeIcon(listing.ProductEntity).Default;

            var priceText = GetListingPriceString(listing);

            var control = new StoreListingControl(listing, priceText, string.Empty, hasBalance, texture);
            control.StoreItemBuyButton.OnButtonDown += _ => OnListingButtonPressed?.Invoke(listing);
            MarketListingsContainer.AddChild(control);
        }
    }

    private string GetListingPriceString(ListingDataWithCostModifiers listing)
    {
        if (listing.Cost.Count < 1)
            return Loc.GetString("store-currency-free");

        var text = string.Empty;
        foreach (var (type, amount) in listing.Cost)
        {
            var currency = _prototypeManager.Index(type);
            text += Loc.GetString("store-ui-price-display", ("amount", amount),
                ("currency", Loc.GetString(currency.DisplayName, ("amount", amount))));
        }

        return text.TrimEnd();
    }

    public void UpdateContracts(List<SpyContractInfo> board, SpyActiveContractInfo? active, int reputation, float nextRotationSeconds)
    {
        ReputationLabel.SetMarkup(Loc.GetString("spy-uplink-ui-reputation", ("value", reputation)));

        var minutes = (int) nextRotationSeconds / 60;
        var seconds = (int) nextRotationSeconds % 60;
        RotationLabel.SetMarkup(Loc.GetString("spy-uplink-ui-rotation", ("time", $"{minutes:D2}:{seconds:D2}")));

        if (active != null && _prototypeManager.TryIndex(active.Id, out var activeContract))
        {
            ActiveContractSection.Visible = true;
            ActiveContractLabel.SetMarkup(Loc.GetString("spy-uplink-ui-active-contract",
                ("name", Loc.GetString(activeContract.Name)), ("reward", active.Reward)));
            ActiveContractProgress.Value = active.Progress;
        }
        else
        {
            ActiveContractSection.Visible = false;
        }

        ContractsContainer.RemoveAllChildren();

        foreach (var info in board)
        {
            if (!_prototypeManager.TryIndex(info.Id, out var contract))
                continue;

            var control = new SpyContractControl(contract, info, active != null);
            control.OnAccept += () => OnContractAccepted?.Invoke(info.Id);
            ContractsContainer.AddChild(control);
        }
    }

    private void OnWithdrawButtonDown(BaseButton.ButtonEventArgs args)
    {
        if (_withdrawWindow is { IsOpen: true })
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        _withdrawWindow = new StoreWithdrawWindow();
        _withdrawWindow.OpenCentered();
        _withdrawWindow.CreateCurrencyButtons(_balance);
        _withdrawWindow.OnWithdrawAttempt += (_, currency, amount) => OnWithdrawAttempt?.Invoke(currency, amount);
    }
}
