using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.FakePlayerCountTab;

// 🌇Sunset🌇 - Host-only tab that pads the player count shown in the launcher. See AdminSystem
// (FakePlayerCountPadding) and GameTicker.StatusShell.cs on the server for where this actually applies.
[GenerateTypedNameReferences]
public sealed partial class FakePlayerCountTab : Control
{
    [Dependency] private readonly IClientConsoleHost _console = default!;

    public FakePlayerCountTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AddButton.OnPressed += _ => SendAdjust("fakeplayercount_add");
        SubtractButton.OnPressed += _ => SendAdjust("fakeplayercount_subtract");
        ResetButton.OnPressed += _ => _console.ExecuteCommand("fakeplayercount_reset");
    }

    private void SendAdjust(string command)
    {
        if (!int.TryParse(AmountInput.Text, out var amount) || amount <= 0)
            return;

        _console.ExecuteCommand($"{command} {amount}");
    }

    public void UpdateCount(int padding)
    {
        CurrentValueLabel.Text = padding.ToString();
    }
}
